# Generated by Django 5.2.11 on 2026-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='dono/')),
            ],
            options={
                'verbose_name': 'Dono da galeria',
                'verbose_name_plural': 'Dono da galeria',
            },
        ),
    ]
